version: "3.7"
services:
    bot:
        image: docker.pkg.github.com/viktorprogger/telegram-rss-bot/bot:${BUILD_TAG}
        user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
        volumes:
            - ./.docker/logs:/var/log
            - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/40-custom.ini:ro
            - ./.docker/data/composer:/root/.composer
            - ./src:/var/www
            - ./.env:/var/.env
        environment:
            TZ: Europe/Moscow
            XDEBUG_CONFIG: "remote_enable=On remote_host=${HOST_IP}"
            PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
            APP_ENV: dev
        env_file:
            - .env
        links:
            - db
            - amqp

    db:
        image: postgres:11-alpine
        restart: on-failure
        volumes:
            - .docker/data/db:/var/lib/postgresql/data
        environment:
            TZ: Europe/Moscow
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_LOGIN}

    amqp:
        image: rabbitmq:3
        restart: on-failure
