version: "3.7"
services:
    bot:
        build:
            dockerfile: .docker/php/Dockerfile
            context: ./
        user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
        volumes:
            - ./.docker/logs:/var/log
            - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/40-custom.ini:ro
            - ./.docker/data/composer:/root/.composer
            - ./app:/var/www
            - ./.env:/var/.env
        environment:
            TZ: Europe/Moscow
        env_file:
            - .env
        links:
            - db
        extra_hosts:
            - host.docker.internal:${HOST_IP:-host.docker.internal}

    db:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: on-failure
        volumes:
            - .docker/data/db:/var/lib/mysql
        environment:
            TZ: Europe/Moscow
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_LOGIN}
