#!/usr/bin/env php
<?php

use hiqdev\composer\config\Builder;
use Psr\Container\ContainerInterface;
use Yiisoft\Yii\Console\Application;

(static function () {
    require_once __DIR__ . '/vendor/autoload.php';

    Yii::setAlias('@runtime', __DIR__ . '/runtime');

    Builder::rebuild();
    $params = require Builder::path('params');

    /** @var ContainerInterface $container */
    $container = $params['console']['container']();
    $container->get(Application::class)->run();
})();
